version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
  - dependency-name: github.com/ElrondNetwork/elrond-go
    versions:
    - 1.1.27
    - 1.1.28
    - 1.1.29
    - 1.1.30
    - 1.1.31
    - 1.1.32
    - 1.1.33
    - 1.1.34
    - 1.1.35
    - 1.1.36
    - 1.1.37
    - 1.1.39
    - 1.1.42
    - 1.1.44
    - 1.1.45
    - 1.1.46
    - 1.1.47
    - 1.1.48
    - 1.1.49
    - 1.1.50
    - 1.1.51
  - dependency-name: github.com/coinbase/rosetta-sdk-go
    versions:
    - 0.6.8
    - 0.6.9
  - dependency-name: github.com/urfave/cli
    versions:
    - 1.22.5
  - dependency-name: github.com/stretchr/testify
    versions:
    - 1.7.0
  - dependency-name: github.com/elastic/go-elasticsearch/v7
    versions:
    - 7.10.0
    - 7.11.0
