#######
# Am am nevoie sa fie o comandata care face undeva in root (~/) un folder
# vine si da checkout la repository ul https://github.com/ElrondNetwork/observing-squad.git
# merge pe branchl de aici rosetta


# in functie de pe parametru primeste o sa porneasca un observer-squad fie spre mainnet (merge in folder rosetta-mainnet
# din branch si porneste de acolo observing-squad ul
# sau testnet merge in folderul rosetta-testnet si porneste de acolo