### NETWORK LIST
POST {{baseUrl}}/network/list HTTP/1.1
Content-Type: application/json

{
}

### NETWORK OPTIONS
POST {{baseUrl}}/network/options HTTP/1.1
Content-Type: application/json

{
    "network_identifier": {
      "blockchain": "Elrond",
      "network": "{{baseNetwork}}"
    },
    "metadata": {}
}


### NETWORK STATUS
POST {{baseUrl}}/network/status HTTP/1.1
Content-Type: application/json

{
  "network_identifier": {
    "blockchain": "Elrond",
    "network": "{{baseNetwork}}"
  },
  "metadata": {}
}

### ACCOUNT BALANCE
POST {{baseUrl}}/account/balance HTTP/1.1
Content-Type: application/json

{
  "network_identifier": {
    "blockchain": "Elrond",
    "network": "{{baseNetwork}}"
  },
  "account_identifier": {
    "address": "erd16x7le8dpkjsafgwjx0e5kw94evsqw039rwp42m2j9eesd88x8zzs75tzry"
  }
}

### BLOCK BY NONCE
POST {{baseUrl}}/block HTTP/1.1
Content-Type: application/json

{
  "network_identifier": {
    "blockchain": "Elrond",
    "network": "{{baseNetwork}}"
  },
  "block_identifier": {
    "index": 143658
  }
}

### CONSTRUCTION PREPROCESS
POST {{baseUrl}}/construction/preprocess HTTP/1.1
Content-Type: application/json

{
  "network_identifier": {
    "blockchain": "Elrond",
    "network": "{{baseNetwork}}"
  },
  "operations": [
    {
      "operation_identifier": {
        "index": 0
      },
      "type": "Transfer",
      "account": {
        "address": "erd1qqqqqqqqqqqqqpgqufjsm9cumjc8kj0rhcxzh90y62c7h66063ssz394p9"
      },
      "amount": {
        "value": "-60457060312024360732",
        "currency": {
          "symbol": "XeGLD",
          "decimals": 18
        }
      }
    },
    {
      "operation_identifier": {
        "index": 1
      },
      "related_operations": [
        {
          "index": 0
        }
      ],
      "type": "Transfer",
      "account": {
        "address": "erd16x7le8dpkjsafgwjx0e5kw94evsqw039rwp42m2j9eesd88x8zzs75tzry"
      },
      "amount": {
        "value": "60457060312024360732",
        "currency": {
          "symbol": "XeGLD",
          "decimals": 18
        }
      }
    }
  ],
  "metadata": {
    "gasPrice": 10000,
    "gasLimit": 1,
    "data": "hello"
  },
  "max_fee": [
    {
      "value": "2000000000",
      "currency": {
        "symbol": "XeGLD",
        "decimals": 18
      },
      "metadata": {

      }
    }
  ],
  "suggested_fee_multiplier": 1.1
}

### CONSTRUCTION PREPROCESS
POST {{baseUrl}}/construction/metadata HTTP/1.1
Content-Type: application/json

{
  "network_identifier": {
    "blockchain": "Elrond",
    "network": "{{baseNetwork}}"
  },
  "options": {
    "feeMultiplier": 1.1,
    "maxFee": "2000000000",
    "receiver": "erd16x7le8dpkjsafgwjx0e5kw94evsqw039rwp42m2j9eesd88x8zzs75tzry",
    "sender": "erd1qqqqqqqqqqqqqpgqufjsm9cumjc8kj0rhcxzh90y62c7h66063ssz394p9",
    "type": "Transfer",
    "value": "60457060312024360732",
    "gasPrice": 1000000000,
    "gasLimit": 58000,
    "data": "hello"
  }
}

### CONSTRUCTION PREPROCESS
POST {{baseUrl}}/construction/payloads HTTP/1.1
Content-Type: application/json

{
  "network_identifier": {
    "blockchain": "Elrond",
    "network": "{{baseNetwork}}"
  },
  "operations": [
    {
      "operation_identifier": {
        "index": 0
      },
      "type": "Transfer",
      "account": {
        "address": "erd1qqqqqqqqqqqqqpgqufjsm9cumjc8kj0rhcxzh90y62c7h66063ssz394p9"
      },
      "amount": {
        "value": "-60457060312024360732",
        "currency": {
          "symbol": "XeGLD",
          "decimals": 18
        }
      }
    },
    {
      "operation_identifier": {
        "index": 1
      },
      "related_operations": [
        {
          "index": 0
        }
      ],
      "type": "Transfer",
      "account": {
        "address": "erd16x7le8dpkjsafgwjx0e5kw94evsqw039rwp42m2j9eesd88x8zzs75tzry"
      },
      "amount": {
        "value": "60457060312024360732",
        "currency": {
          "symbol": "XeGLD",
          "decimals": 18
        }
      }
    }
  ],
  "metadata": {
    "chainID": "local-testnet",
    "gasLimit": 58000,
    "gasPrice": 1000000000,
    "nonce": 0,
    "receiver": "erd16x7le8dpkjsafgwjx0e5kw94evsqw039rwp42m2j9eesd88x8zzs75tzry",
    "sender": "erd1qqqqqqqqqqqqqpgqufjsm9cumjc8kj0rhcxzh90y62c7h66063ssz394p9",
    "value": "60457060312024360732",
    "version": 1,
    "data": "aGVsbG8="
  }
}

